# permissions for end users to edit dependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dependency-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dependency-operator2
    app.kubernetes.io/part-of: dependency-operator2
    app.kubernetes.io/managed-by: kustomize
  name: dependency-editor-role
rules:
- apiGroups:
  - dep.example.com
  resources:
  - dependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dep.example.com
  resources:
  - dependencies/status
  verbs:
  - get
